version: '3'

services:
  app:
    build: .
    restart: on-failure
    env_file:
      - ./app.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5432:5432
    env_file:
      - ./app.env
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app

volumes:
  postgres:

networks:
  app:
    driver: bridge